/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scramados.things;

import org.reflections.util.ClasspathHelper;

public class TopApp {
    public static void main(String[] args) {
        System.out.println(ClasspathHelper.forPackage("com.scramados"));
    }
}
